2018-12-12 16:08:56,955 - test - INFO - 开始测试
2018-12-12 16:08:56,955 - test - ERROR - tests
Traceback (most recent call last):
  File "D:/PycharmProjects/python_study/test/log_test.py", line 7, in <module>
    r = 10/0
ZeroDivisionError: division by zero
2018-12-12 16:08:56,965 - test - INFO - end
