2018-12-12 16:08:56,955 - test - ERROR - log_test  - 10 - tests
Traceback (most recent call last):
  File "D:/PycharmProjects/python_study/test/log_test.py", line 7, in <module>
    r = 10/0
ZeroDivisionError: division by zero
